name: CI/CD Workflow

on:
  pull_request:
    types: [closed]  # Trigger only when a PR is closed (merged or not)
    branches: [main]

jobs:
  test_and_build:
    if: github.event.pull_request.merged == true  # Run only if the PR was merged
    name: Run Tests and Build Artifact
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Set up JDK 17 (Java 17 environment)
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      # Step 3: Run tests and ensure the build is successful
      - name: Run Tests (mvn clean install)
        run: |
          mvn clean install

      # Step 4: Verify the JAR file exists
      - name: Check if JAR file exists
        run: |
          if [ ! -f target/CloudApplication-0.0.1-SNAPSHOT.jar ]; then
            echo "JAR file not found! Build may have failed."
            exit 1
          else
            echo "JAR file exists."
          fi

      # Step 5: Archive the build artifact in a separate folder
      - name: Archive Build Artifact
        run: mkdir -p artifacts

      # Step 6: Copy the JAR/WAR file to the artifacts directory
      - name: Copy Build Artifact
        run: cp target/CloudApplication-0.0.1-SNAPSHOT.jar artifacts/

      # Step 7: Upload the build artifact (JAR/WAR) so it can be used in subsequent jobs
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: artifacts/

  packer_build:
    name: Build Custom AMI with Packer
    runs-on: ubuntu-latest
    needs: test_and_build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: build-artifact
          path: artifacts/

      - name: Check File Existence
        run: |
          if [ -f packer/csye6225.service ]; then
            echo "csye6225.service file exists."
          else
            echo "csye6225.service file is missing."
            exit 1
          fi

      - name: Set Permissions for Service File
        run: |
          chmod 644 packer/csye6225.service

      - name: Install Packer
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install packer

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.IAM_USER_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.IAM_USER_SECRET_KEY }}
          aws-region: us-east-1

      - name: Build AMI with Packer
        run: |
          packer init packer/aws-ubuntu.pkr.hcl
          packer build \
            -var "artifact_path=artifacts/CloudApplication-0.0.1-SNAPSHOT.jar" \
            -var "DATABASE_ENDPOINT=${{ secrets.DATABASE_ENDPOINT }}" \
            -var "DATABASE_NAME=${{ secrets.DATABASE_NAME }}" \
            -var "DB_USERNAME=${{ secrets.DB_USERNAME }}" \
            -var "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" \
            packer/aws-ubuntu.pkr.hcl
