name: CI/CD Workflow

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]


jobs:
  test_and_build:
    name: Run Tests and Build Artifact
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Set up JDK 17 (Java 17 environment)
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      # Step 3: Run tests and ensure the build is successful
      - name: Run Tests (mvn clean install)
        run: |
          mvn clean install

      # Step 4: Package the application into a JAR/WAR
      - name: Package Application (mvn clean package)
        run: |
          mvn clean package

      # Step 5: Archive the build artifact in a separate folder
      - name: Archive Build Artifact
        run: mkdir -p artifacts

      # Step 6: Copy the JAR/WAR file to the artifacts directory
      - name: Copy Build Artifact
        run: cp target/CloudApplication-0.0.1-SNAPSHOT.jar artifacts/

      # Step 7: Upload the build artifact (JAR/WAR) so it can be used in subsequent jobs
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: artifacts/

  packer_build:
    name: Build Custom AMI with Packer
    runs-on: ubuntu-latest
    needs: test_and_build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: build-artifact
          path: artifacts/

      - name: Install Packer
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install packer

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.SERVICE_ACCOUNT_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SERVICE_ACCOUNT_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Build AMI with Packer
        run: |
          packer init aws-ubuntu.pkr.hcl
          packer build \
            -var "artifact_path=artifacts/CloudApplication-0.0.1-SNAPSHOT.jar" \
            -var "DATABASE_ENDPOINT=${{ secrets.DATABASE_ENDPOINT }}" \
            -var "DATABASE_NAME=${{ secrets.DATABASE_NAME }}" \
            -var "DB_USERNAME=${{ secrets.DB_USERNAME }}" \
            -var "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" \
            aws-ubuntu.pkr.hcl
