name: CI/CD Workflow

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]


jobs:
  test_and_build:
    name: Run Tests and Build Artifact
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Run Tests and Build
        run: |
          ./mvnw clean install

      - name: Archive Build Artifact
        run: mkdir -p artifacts
      - name: Copy Build Artifact
        run: cp target/CloudApplication-0.0.1-SNAPSHOT.jar artifacts/

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: artifacts/

  packer_build:
    name: Build Custom AMI with Packer
    runs-on: ubuntu-latest
    needs: test_and_build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: build-artifact
          path: artifacts/

      - name: Install Packer
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install packer

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Build AMI with Packer
        run: |
          packer init aws-ubuntu.pkr.hcl
          packer build \
            -var "artifact_path=artifacts/CloudApplication-0.0.1-SNAPSHOT.jar" \
            -var "DATABASE_ENDPOINT=${{ secrets.DATABASE_ENDPOINT }}" \
            -var "DATABASE_NAME=${{ secrets.DATABASE_NAME }}" \
            -var "DB_USERNAME=${{ secrets.DB_USERNAME }}" \
            -var "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" \
            aws-ubuntu.pkr.hcl
