name: CI/CD Workflow

on:
  pull_request:
    branches:
      - main

env:
  ENV: demo

jobs:
  test_and_build:
    name: Run Tests and Build Artifact
    runs-on: ubuntu-latest

    steps:
      - name: Debug ENV Variable
        run: |
          echo "ENV variable in test_and_build job: ${{ env.ENV }}"

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Run Tests (mvn clean install)
        run: |
          mvn clean install

      - name: Check if JAR file exists
        run: |
          if [ ! -f target/CloudApplication-0.0.1-SNAPSHOT.jar ]; then
            echo "JAR file not found! Build may have failed."
            exit 1
          else
            echo "JAR file exists."
          fi

      - name: Archive Build Artifact
        run: mkdir -p artifacts

      - name: Copy Build Artifact
        run: cp target/CloudApplication-0.0.1-SNAPSHOT.jar artifacts/

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: artifacts/

  packer_build:
    name: Build Custom AMI with Packer
    runs-on: ubuntu-latest
    needs: test_and_build

    outputs:
      ami_id: ${{ steps.build_image.outputs.ami_id }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: build-artifact
          path: artifacts/

      - name: Check File Existence
        run: |
          if [ -f packer/csye6225.service ]; then
            echo "csye6225.service file exists."
          else
            echo "csye6225.service file is missing."
            exit 1
          fi

      - name: Set Permissions for Service File
        run: chmod 644 packer/csye6225.service

      - name: Install Packer
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install packer

      - name: Set Environment Secrets
        id: set-secrets
        run: |
          if [[ "${{ env.ENV }}" == "dev" ]]; then
            echo "AWS_ACCESS_KEY_ID=${{ secrets.IAM_USER_ACCESS_KEY_ID }}" >> $GITHUB_ENV
            echo "AWS_SECRET_ACCESS_KEY=${{ secrets.IAM_USER_SECRET_KEY }}" >> $GITHUB_ENV
          elif [[ "${{ env.ENV }}" == "demo" ]]; then
            echo "AWS_ACCESS_KEY_ID=${{ secrets.IAM_USER_ACCESS_KEY_ID_DEMO }}" >> $GITHUB_ENV
            echo "AWS_SECRET_ACCESS_KEY=${{ secrets.IAM_USER_AWS_SECRET_ACCESS_KEY_DEMO }}" >> $GITHUB_ENV
          else
            echo "Unknown environment: ${{ env.ENV }}"
            exit 1
          fi

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Build AMI with Packer and Extract AMI ID
        id: build_image
        run: |
          packer init packer/aws-ubuntu.pkr.hcl
          AMI_OUTPUT=$(packer build -var "artifact_path=artifacts/CloudApplication-0.0.1-SNAPSHOT.jar" packer/aws-ubuntu.pkr.hcl)
          echo "$AMI_OUTPUT"
          ami_id=$(echo "$AMI_OUTPUT" | grep -oP '(?<=us-east-1: )ami-[a-zA-Z0-9]+')
          if [ -z "$ami_id" ]; then
            echo "Failed to extract AMI ID from the Packer build output!"
            exit 1
          fi
          echo "::set-output name=ami_id::$ami_id"
          echo "Extracted AMI ID: $ami_id"

  deploy_to_autoscaling:
    name: Deploy Application to Auto-Scaling Group
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Environment Secrets
        id: set-secrets
        run: |
          if [[ "${{ env.ENV }}" == "dev" ]]; then
            echo "AWS_ACCESS_KEY_ID=${{ secrets.IAM_USER_ACCESS_KEY_ID }}" >> $GITHUB_ENV
            echo "AWS_SECRET_ACCESS_KEY=${{ secrets.IAM_USER_SECRET_KEY }}" >> $GITHUB_ENV
          elif [[ "${{ env.ENV }}" == "demo" ]]; then
            echo "AWS_ACCESS_KEY_ID=${{ secrets.IAM_USER_ACCESS_KEY_ID_DEMO }}" >> $GITHUB_ENV
            echo "AWS_SECRET_ACCESS_KEY=${{ secrets.IAM_USER_AWS_SECRET_ACCESS_KEY_DEMO }}" >> $GITHUB_ENV
          else
            echo "Unknown environment: ${{ env.ENV }}"
            exit 1
          fi

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Retrieve Launch Template ID from AWS
        id: launch_template
        run: |
          LAUNCH_TEMPLATE_ID=$(aws ec2 describe-launch-templates \
            --filters Name=launch-template-name,Values=csye6225_asg \
            --query 'LaunchTemplates[0].LaunchTemplateId' --output text)
          if [ -z "$LAUNCH_TEMPLATE_ID" ]; then
            echo "Failed to retrieve Launch Template ID from AWS."
            exit 1
          fi
          echo "LAUNCH_TEMPLATE_ID=$LAUNCH_TEMPLATE_ID" >> $GITHUB_ENV

      - name: Create New Launch Template Version
        run: |
          aws ec2 create-launch-template-version \
            --launch-template-id ${{ env.LAUNCH_TEMPLATE_ID }} \
            --source-version '$Latest' \
            --launch-template-data '{"ImageId":"'"${{ needs.packer_build.outputs.ami_id }}"'"}'

          aws ec2 modify-launch-template \
            --launch-template-id ${{ env.LAUNCH_TEMPLATE_ID }} \
            --default-version '$Latest'

      - name: Start Instance Refresh
        id: refresh
        run: |
          REFRESH_ID=$(aws autoscaling start-instance-refresh \
            --auto-scaling-group-name app_asg \
            --preferences '{"MinHealthyPercentage":90}' \
            --query 'InstanceRefreshId' \
            --output text)
          if [ -z "$REFRESH_ID" ]; then
            echo "Failed to start instance refresh."
            exit 1
          fi
          echo "REFRESH_ID=$REFRESH_ID" >> $GITHUB_ENV

      - name: Wait for Instance Refresh to Complete
        run: |
          while true; do
            STATUS=$(aws autoscaling describe-instance-refreshes \
              --auto-scaling-group-name app_asg \
              --instance-refresh-ids "${REFRESH_ID}" \
              --query 'InstanceRefreshes[0].Status' \
              --output text)
            echo "Instance Refresh Status: $STATUS"
            if [[ "$STATUS" = "Successful" ]]; then
              echo "Instance refresh completed successfully."
              break
            elif [[ "$STATUS" = "Failed" || "$STATUS" = "Cancelled" ]]; then
              echo "Instance refresh failed or was cancelled."
              exit 1
            else
              echo "Instance refresh is in progress. Checking again in 30 seconds..."
              sleep 30
            fi
          done
