name: Packer CI Status Check

on:
  pull_request:
    branches:
      - main

jobs:
  packer-check:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Set up HashiCorp Packer
      - name: Set up HashiCorp Packer
        uses: hashicorp/setup-packer@v2

      # Step 3: Initialize Packer Plugins
      - name: Initialize Packer Plugins
        run: |
          packer init packer/aws-ubuntu.pkr.hcl

      # Step 4: Run Packer fmt to check formatting issues
      - name: Run Packer fmt check
        run: |
          packer fmt -check -diff packer/aws-ubuntu.pkr.hcl
        continue-on-error: false  # Fail if formatting is incorrect

      # Step 5: Ensure no files were modified by packer fmt
      - name: Fail workflow if packer fmt modified any files
        run: |
          git diff --exit-code || exit 1  # Fail if any file is modified

      # Step 6: Validate the Packer template
      - name: Run Packer validate
        run: |
          packer validate \
            -var "DATABASE_ENDPOINT=${{ secrets.DATABASE_ENDPOINT }}" \
            -var "DATABASE_NAME=${{ secrets.DATABASE_NAME }}" \
            -var "DB_USERNAME=${{ secrets.DB_USERNAME }}" \
            -var "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" \
            -var "artifact_path=artifacts/CloudApplication-0.0.1-SNAPSHOT.jar" \
            packer/aws-ubuntu.pkr.hcl
        continue-on-error: false  # Fail if validation fails
